[workspace]
members = [
    "graph-api-lib",
    "graph-api-derive",
    "graph-api-test",
    "graph-api-benches",
    "graph-api-petgraph",
    "graph-api-simplegraph",
    "graph-api-book",
]

resolver = "2"

[workspace.dependencies]
petgraph = "0.7.1"