[package]
name = "graph-api-lib"
version = "0.1.0"
edition = "2021"

[features]
petgraph = [
    "dep:petgraph"
]

[dependencies]
petgraph = { version = "0.6.4", optional = true }
uuid = { version = "1.11.0", features = ["v4"] }
thiserror = "2.0.3"
