[package]
name = "graph-api-test"
version = "0.1.0"
edition = "2021"

[features]
default = []
vertex-index = []
vertex-label-index = []
vertex-full-text-index = []
vertex-ordered-index = []
edge-label-index = []


[dependencies]
graph-api-lib = { path = "../graph-api-lib" }
graph-api-derive = { path = "../graph-api-derive" }
thiserror = "2.0.3"
proptest = "1.5.0"
uuid = { version = "1.11.0", features = ["v4"] }