[book]
authors = ["bryn cooke"]
language = "en"
multilingual = false
src = "src"
title = "graph-api"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/BrynCooke/graph-api"
git-repository-icon = "fa-github"

[preprocessor.variables.variables]
version = "0.1.2"  # Legacy variable - will be removed once all md files are updated
lib_version = "0.1.2"
derive_version = "0.1.1"
simplegraph_version = "0.1.2"
petgraph_version = "0.1.2"
test_version = "0.1.2"
benches_version = "0.1.2"