[book]
authors = ["bryn cooke"]
language = "en"
multilingual = false
src = "src"
title = "graph-api"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/BrynCooke/graph-api"
git-repository-icon = "fa-github"

[preprocessor.variables.variables]
version = "0.1.2"