[book]
authors = ["bryn cooke"]
language = "en"
multilingual = false
src = "src"
title = "graph-api"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/BrynCooke/graph-api"
git-repository-icon = "fa-github"

[output.linkcheck]

[preprocessor.variables.variables]
version = "0.2.0"  # Legacy variable - will be removed once all md files are updated
lib_version = "0.2.0"
derive_version = "0.1.4"
simplegraph_version = "0.2.0"
petgraph_version = "0.1.5"
test_version = "0.2.0"
benches_version = "0.2.0"