name: Continuous Integration (Book)
on:
  push:
    branches:
      - "main"
    paths:
      - 'graph-api-book/**'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ "main" ]
    paths:
      - 'graph-api-book/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_book:
    name: Build Book
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Add mdBook plugins
        run: |
          cargo install mdbook-variables
          cargo install mdbook-linkcheck

      - name: Build mdBook
        run: mdbook build graph-api-book
