name: Continuous Integration
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous_integration:
    name: Build, Test, Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@cargo-nextest
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Build
        run: just build
      - name: Test
        run: just test
      - name: Clippy
        run: just lint

  build_book:
    name: Build Book
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Add mdBook plugins
        run: |
          cargo install mdbook-variables
          cargo install mdbook-linkcheck

      - name: Build mdBook
        run: mdbook build graph-api-book
