name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous_integration:
    name: Build, Test, Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@cargo-nextest
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Build
        run: just build
      - name: Test
        run: just test
      - name: Clippy
        run: just lint
