name: Major Version Bump

on:
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'Title for the version bump PR'
        required: true
        default: 'chore: Major version bump'

jobs:
  major-version-bump:
    name: Major Version Bump
    if: ${{ github.repository_owner == 'bryncooke' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-major-version-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Get next major version from graph-api-lib
        id: calculate_version
        run: |
          # Get current version from graph-api-lib
          current_version=$(grep -m 1 'version = ' "graph-api-lib/Cargo.toml" | cut -d '"' -f 2)
          echo "Current version: $current_version"
          
          # Extract major version and increment it
          major_version=$(echo "$current_version" | cut -d '.' -f 1)
          new_major=$((major_version + 1))
          new_version="${new_major}.0.0"
          
          echo "New version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
      
      - name: Run release-plz to create PR with major version
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          version: ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PLZ_PR_TITLE: "${{ github.event.inputs.pr_title }}: v${{ env.NEW_VERSION }}"