name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@cargo-nextest
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run tests graph-api-derive
        run: cargo nextest run -p graph-api-derive
      - name: Run tests graph-api-simplegraph
        run: cargo nextest run -p graph-api-simplegraph
      - name: Run tests graph-api-petgraph
        run: cargo nextest run -p graph-api-petgraph
      - name: Clippy
        run: cargo clippy -- -D warnings
