use graph_api_lib::{Graph, VertexReference};
use graph_api_simplegraph::SimpleGraph;
use graph_api_test::{Vertex, VertexExt, VertexIndex, populate_graph};

// ANCHOR: all
// Function demonstrating various ways to use the filter step
pub fn filter_examples() {
    // Create a new graph
    let mut graph = SimpleGraph::new();
    // Populate the graph with test data
    let _refs = populate_graph(&mut graph);

    // ANCHOR: basic_filter
    // Basic filter using a closure
    let adult_people = graph
        .walk()
        .vertices(VertexIndex::person())
        .filter_by_person(|person, _| person.age() >= 18)
        .collect::<Vec<_>>();

    println!("Found {} adults", adult_people.len());
    // ANCHOR_END: basic_filter

    // ANCHOR: type_specific_filter
    // Use the type-specific filter methods generated by the VertexExt derive macro
    let people_named_b = graph
        .walk()
        .vertices(VertexIndex::person())
        .filter_by_person(|person, _| {
            // This closure gets a strongly-typed view of the Person data
            person.name().starts_with('B')
        })
        .collect::<Vec<_>>();

    println!(
        "Found {} people whose names start with B",
        people_named_b.len()
    );
    // ANCHOR_END: type_specific_filter

    // ANCHOR: chained_filters
    // Chain multiple filters for complex conditions
    let specific_people = graph
        .walk()
        .vertices(VertexIndex::person())
        // First filter: age range
        .filter_by_person(|person, _| person.age() > 25 && person.age() < 40)
        // Second filter: name contains 'y'
        .filter_by_person(|person, _| person.name().contains('y'))
        .collect::<Vec<_>>();

    println!(
        "Found {} people aged 26-39 with 'y' in their name",
        specific_people.len()
    );
    // ANCHOR_END: chained_filters

    // ANCHOR: context_filter
    // Use filter with context
    let result = graph
        .walk()
        .vertices(VertexIndex::person())
        .push_context(|v, _| {
            // Store original vertex in context
            if let Vertex::Person { name, .. } = v.weight() {
                name.clone()
            } else {
                String::new()
            }
        })
        .filter(|_, ctx| {
            // Filter based on context
            ctx.len() > 3
        })
        .collect::<Vec<_>>();

    println!(
        "Found {} people with names longer than 3 characters",
        result.len()
    );
    // ANCHOR_END: context_filter
}
// ANCHOR_END: all
